### ISSUE TITLE
前后端的职责划分

### ISSUE THREAD

**Issue by zhanzizhen** [zhanzizhen/code-experience#38]
### 根本思路

后端只关心数据和数据逻辑，ui类的数据应该保存在前端，由前端控制。在具体一点，就是存在bundle.js文件里面。

### 为什么

1. 后端对展示类的数据是陌生的，而前端由于经常跟界面打交道，对这些负责ui的数据会更熟悉，也更加敏感。
2. 为了前后端分离，前端对ui数据的更改不需要经过后端。

### 实例

下面是一个反例：

```json
[
  {
    "id": 1,
    "color": "red",
    "icon": "iconfont-person"
  },
  {
    "id": 2,
    "color": "black",
    "icon": "iconfont-tool"
  },
  {
    "id": 3,
    "color": "brown",
    "icon": "iconfont-home"
  }
];

```

**Comment by zhenghaohe** [comment]
能请教一下为什么这个是一个反例吗？

**Comment by yicone** [comment]
> 能请教一下为什么这个是一个反例吗？

可能是指后端返回了这些数据😄

**Comment by zhanzizhen** [comment]
> 能请教一下为什么这个是一个反例吗？

@zhenghaohe sorry，没有描述清楚。可看这篇：https://github.com/zhanzizhen/my-blog/blob/main/others/%E5%89%8D%E5%90%8E%E7%AB%AF%E7%9A%84%E8%81%8C%E8%B4%A3%E5%88%92%E5%88%86.md
